// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnDnHW0HSpC6WcLOM68kCgKza630gryng',
    appId: '1:314082432287:web:e49d3fb79079d29e654c2a',
    messagingSenderId: '314082432287',
    projectId: 'campus-expense-split-av',
    authDomain: 'campus-expense-split-av.firebaseapp.com',
    storageBucket: 'campus-expense-split-av.firebasestorage.app',
    measurementId: 'G-ZV4LB45565',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfHqPpRybg1e6yKIuWIDUMsj--IfFmrwo',
    appId: '1:314082432287:android:8f66e7bfe49e325b654c2a',
    messagingSenderId: '314082432287',
    projectId: 'campus-expense-split-av',
    storageBucket: 'campus-expense-split-av.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM9PpOgECGPlsIGNEjnjVrhV-0zrpLZ88',
    appId: '1:314082432287:ios:d981056628e3e565654c2a',
    messagingSenderId: '314082432287',
    projectId: 'campus-expense-split-av',
    storageBucket: 'campus-expense-split-av.firebasestorage.app',
    iosBundleId: 'com.example.campusexpensesplit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM9PpOgECGPlsIGNEjnjVrhV-0zrpLZ88',
    appId: '1:314082432287:ios:d981056628e3e565654c2a',
    messagingSenderId: '314082432287',
    projectId: 'campus-expense-split-av',
    storageBucket: 'campus-expense-split-av.firebasestorage.app',
    iosBundleId: 'com.example.campusexpensesplit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnDnHW0HSpC6WcLOM68kCgKza630gryng',
    appId: '1:314082432287:web:e4c41bb114044bb7654c2a',
    messagingSenderId: '314082432287',
    projectId: 'campus-expense-split-av',
    authDomain: 'campus-expense-split-av.firebaseapp.com',
    storageBucket: 'campus-expense-split-av.firebasestorage.app',
    measurementId: 'G-QZN9LX206L',
  );
}
